### ISSUE TITLE
Block input when the game ends

### ISSUE THREAD

**Issue by NStefan002** [willothy/strat-hero.nvim#4]
## Problem
When I'm in time trouble and just spamming `hjkl` more often than not when the time runs out I accidentally start the new round without seeing the score.
## Solution
Block user input for some time (e.g. 1 second) right after the game ends (when the score text is displayed), or specify the new keymap for starting the game (e.g. `n` or `s`).

**Comment by willothy** [comment]
Good point, I've run into this as well. Thanks! I'll update this ASAP.

**Comment by willothy** [comment]
Added a 2.5 second timeout for now, can be adjusted in the future if needed :)

**Comment by NStefan002** [comment]
Feels good! Thanks
